Feature styles
voyansi/package-manager pull request #71
Opened 2021-01-28 13:46 UTC by franpossetto

Global styles have been added.

styles forlder contains all the files related with global css.
-voyansi.scss file links all the file that manage styling. You should not write your styles on this file. it only have to contain imports.
-variables/colors.scss file contains variables related with colors. You should use the the derivated variables. It is an easy way to understand where the color should be used.
-variables/colors.scss file contains voyansi custom classes for text.
-components/helpers.scss contains classes related with Flexbox.
-components/buttons.scss contains classes related with buttons. Create a scss file for a component if you think it could have many classes related.
-components/generic.scss contains all the code that are not in the described files.
-variables.scss use this file to modify vuetify sass variables.

2021-01-28 18:00 UTC, mpothier requested changes
Nice work! This is a great styling infrastructure to use moving forward.
In addition to the in-line comments, here are a few requests/comments:
- The font weight is a bit too light in most cases. See if you can use multiple font weights for things like title/subtitle/body, etc.
- Change the sidebar color to something from the branding colors
- I think the purple primary color on the buttons feels a bit too dark. Is there a lighter shade from our branding colors, or another lighter accent color instead?
- Hold off on developing content for the Settings page for now
- Try updating your branch by merging in the latest commits from `dev`, which will hopefully resolve some of the errors you're seeing. Resolve any git conflicts you encounter (it looks like there will be one on the vuetify plugins file).

2021-01-28 18:16 UTC, franpossetto commented on src/components/browse/ControlBar.vue
> +      <v-btn-toggle mandatory v-model="tempDisplayToggle" class="vo-toggle-buttons">
Ok, I converted it into a class.

2021-01-28 20:39 UTC, franpossetto commented on src/views/Settings.vue
>  </style>
ok. perfect

2021-01-29 14:43 UTC, franpossetto commented on src/styles/variables/fonts.scss
> +}
I don´t think so. I think it is a way to define our design, having some rules. For example, font-weight could be solved by assigning a weight to certain elements as Title, subtitle, text. 

Other alternative could be has classes with just one responsibility, for example:

.voyansi-weight-700 {
  font-weight: 700;
}

.voyansi-weight-600 {
  font-weight: 600;
}

.voyansi-weight-text {
  font-weight: 500;
}

What do you think?

2021-01-29 20:14 UTC, mpothier requested changes
A few more quick changes:
- change sidebar color to something from our branding colors
- change button color to a lighter version of the purple (assuming there's one from branding)
- change button text font weight to be slightly heavier
- remove package-lock.json file; if you added any new packages, make sure to use `yarn add ...` instead of `npm`

2021-01-29 20:14 UTC, mpothier commented on src/styles/variables.scss
> +$btn-font-weight: 300;
Let's make the button text font weight a bit heavier (500?) to match the baseline text

2021-02-02 19:28 UTC, merged